Mrnet base
materialsproject/mrnet pull request #113
Opened 2021-04-19 20:45 UTC by KhanWhale

Revamp graph structure:
Rather than having A + PR_B -> C and B + PR_A -> C reaction nodes, compress into just one A + B -> C node and abstract away PR/Reactant identification. 
Still need to update concerteds and rnmc (due to concerted dependence).

2021-04-23 23:58 UTC, samblau requested changes

2021-04-23 23:58 UTC, samblau commented on src/mrnet/network/reaction_network.py
> +            elif "PR_" in step:  # flag
So first off, I don't totally remember when parse_path was introduced, and it seems weird to me that we have both parse_path and characterize_path. But also, I believe you said that PR solving was all working, and yet parse_path is still checking for "PR_"? Does that mean that parse_path isn't necessary to PR solving?

2021-04-23 23:58 UTC, samblau commented on src/mrnet/network/reaction_network.py
> +                        if (
Again, sad times. At least wrap this in a function or something?

2021-04-23 23:58 UTC, samblau commented on src/mrnet/network/reaction_network.py
> +                    reactants = [reac.replace("PR_", "") for reac in reactants]  # flag
Can this line just be removed? It seems like the previous line should work as intended given "A+B,C" or "A,B"

2021-04-23 23:58 UTC, samblau commented on tests/network/test_reaction_network.py
> +                    for i in range(
This chunk could use some comments. I mostly get what's happening here, but a year in the future it's possible I'd find it totally incomprehensible

2021-04-26 22:11 UTC, KhanWhale commented
RNMC and concerteds updated as well.

2021-04-28 17:55 UTC, hpatel1567 approved these changes

2021-04-29 00:24 UTC, samblau approved these changes

2021-04-29 00:25 UTC, samblau commented
Once Linting passes, this can be merged! Wouldn't hurt to pull in Main one more time once you're all done. Thanks again for your great work!

2021-04-29 17:13 UTC, merged